name: deploy-to-beanstalk

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      # - name: Checkout node version
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14

      - name: Creating zip
        run: zip -r deploy.zip ./ -x "*.git*" "*node_modules*" "*.env*"
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Upload zip to S3 bucket
        run: aws s3 cp deploy.zip s3://demo-nextjs-app/
      
      - name: Create new ElasticBeanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name test-application \
          --source-bundle S3Bucket="demo-nextjs-app",S3Key="deploy.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
      
      - name: Update ElasticBeanstalk environment
        run: aws elasticbeanstalk update-environment --environment-name Testapplication-env-1 --version-label "ver-${{ github.sha }}"