name: deploy-to-beanstalk

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
          
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - run: yarn config set unsafe-perm true
      - run: yarn install
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: load variables from .env
        uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: "DB_URL"
          env_variable_name: "DATABASE_URL"
        
      - run: yarn build
      - run: yarn run generate-zip
      
      - name: Upload zip to S3 bucket
        run: aws s3 cp deploy.zip s3://intellikam/
      
      - name: Create new ElasticBeanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name intellikam \
          --source-bundle S3Bucket="intellikam",S3Key="deploy.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
      
      - name: Update ElasticBeanstalk environment
        run: aws elasticbeanstalk update-environment --environment-name Intellikam-env --version-label "ver-${{ github.sha }}"
